### ISSUE TITLE
buttons are too short.

### ISSUE THREAD

**Issue by Cryptorial0** [inputlabs/alpakka_case#15]
I've printed the front case and all the buttons and all of them apart from the joystick, scrollwheel and the dhat don't come out the other side which makes them unpressable.
![WhatsApp Image 2023-12-13 at 00 12 31](https://github.com/inputlabs/alpakka_case/assets/109611374/8f7e5e3a-7a70-4b8b-ae3b-ca98f53ebef9)

**Comment by przymi** [comment]
Hi Cryptorial,

could you show us a picture from the other side? And perhaps of just the buttons from the side? From the picture it looks like your top part has a significant "elephants foot" (https://www.3dsourced.com/guides/3d-print-elephants-foot/). So that may prevent the buttons from going in properly. This is a rather common problem with 3D printers. Accordingly, you would have to adjust your printer settings and re-print. Alternatively, you could sand off the expanded lower part of the prints.

**Comment by Cryptorial0** [comment]
It looks like it is indeed a case of elephants foot, I am probably going to to reprint it entirely as I don't have the time nor the tools to sand it down. 
Thanks.
